on:
  schedule: 
  - cron: "*/1 * * * *" 

jobs:
  repo-sync:
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: repo-sync/github-sync@v2
      name: Sync repo to branch
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: gh-pages
        destination_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: setup git config
        run: |
          git config user.name "parama4u"
          git config user.email "parama4u@gmail.com"
    - name: merge master and push
      run: | 
            git checkout wip
            git add .
            git merge master --allow-unrelated-histories
            git push 
    # - uses: repo-sync/pull-request@v2
    #   name: Create pull request
    #   with:
    #     source_branch: ${{ secrets.INTERMEDIATE_BRANCH }}
    #     destination_branch: master
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
